### ISSUE TITLE
[BUG] when compiling gives GLSL error message

### ISSUE THREAD

**Issue by DjoykeAbyah** [codam-coding-college/MLX42#137] opened 2024-04-01 11:42 UTC
Hi! When trying to run cub3d we get " 0:2(201): error: sampler arrays indexed with non-constant expressions are forbidden in GLSL 1.30 and later ", as an error message.

**To Reproduce**
1. Go to 'https://github.com/DjoykeAbyah/42_CUB3D'
2. clone repo
3. make or make re
4. run ./cub3d ./maps/basic.cub
5. see error.

**Expected behavior**
It should not give an error

**Desktop (please complete the following information):**
- Apple Inc. iMac18,3
- Ubuntu 22.04.3 LTS

**Additional context**
We tried to reduce our code to the bare minimum to see where it goes wrong. just have a main with init.mlx in there and a infinite while loop. That still gave the same error.
Also on our Windows laptop and Mac laptop it worked just fine.

**Comment by W2Wizard** [comment] 2024-04-01 13:50
Duplicate of #136

Will fix it very soon.

**Comment by DjoykeAbyah** [comment] 2024-04-01 13:57
Thanks!!

**Comment by W2Wizard** [comment] 2024-04-01 17:00
Fixed in ca0f163

**Closed by W2Wizard** 2024-04-01 17:00 UTC
Labels: Bug, Duplicate
